#!/usr/bin/env python3
"""Check that a node's REST responses match the schemas this reference publishes.

The generated OpenAPI spec describes 107 routes, almost all of them queries. If a
schema disagrees with what a node returns, anyone generating a client from it
reads the wrong field names and gets undefined back. That defect shipped once:
the spec documented `nextKey` while the gateway emits `next_key`.

Schemathesis does the comparison. This wraps it with the two things it cannot
know: which real values to put in path parameters, and how to report a mismatch
as a documentation defect rather than as an API bug.

Point it at a local simapp rather than a public endpoint. simapp runs the exact
SDK version the pages document and registers every module, so a failure is a real
disagreement instead of a version or module-availability artifact.

Usage:
    python3 conformance.py --version latest --url http://localhost:1317
"""

import argparse
import json
import subprocess
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent


def get(url: str):
    with urllib.request.urlopen(url, timeout=15) as response:
        return json.load(response)


def discover_fixtures(base: str) -> dict:
    """Learn real parameter values from the chain under test.

    No tool can guess a valid bech32 address for a given chain, and a generated
    one fails the checksum. Asking the chain is the only reliable source, and it
    keeps the fixtures correct when the chain is rebuilt.
    """
    fixtures = {}

    params = get(f"{base}/cosmos/staking/v1beta1/params")
    fixtures["denom"] = params["params"]["bond_denom"]

    validators = get(f"{base}/cosmos/staking/v1beta1/validators?pagination.limit=1")
    if validators.get("validators"):
        fixtures["validator_addr"] = validators["validators"][0]["operator_address"]

    accounts = get(f"{base}/cosmos/auth/v1beta1/accounts?pagination.limit=5")
    for account in accounts.get("accounts", []):
        address = account.get("address") or account.get("base_account", {}).get("address")
        if address and address.startswith("cosmos1"):
            fixtures["address"] = address
            break

    block = get(f"{base}/cosmos/base/tendermint/v1beta1/blocks/latest")
    fixtures["height"] = block["block"]["header"]["height"]

    return fixtures


# Path parameter names in the generated spec, mapped to the fixture that fits.
# Names come from the protos, so they are stable across SDK versions.
PARAMETER_FIXTURES = {
    "address": "address",
    "delegator_addr": "address",
    "delegatorAddr": "address",
    "granter": "address",
    "grantee": "address",
    "depositor": "address",
    "voter": "address",
    "validator_addr": "validator_addr",
    "validatorAddr": "validator_addr",
    "denom": "denom",
    "height": "height",
}


def write_config(config_path: Path, spec: Path, fixtures: dict) -> None:
    """A schemathesis.toml pinning parameters and running one check.

    Only response_schema_conformance is enabled. The other checks assert things
    about an API under development, which is not what this is: the node is
    correct by definition and the documentation is what may be wrong.
    """
    lines = [
        "# Generated by conformance.py. Values are discovered from the chain",
        "# under test, so this file is disposable rather than maintained.",
        "",
        "[checks]",
        "enabled = false",
        "response_schema_conformance.enabled = true",
        "",
        "[parameters]",
    ]
    for name, fixture in PARAMETER_FIXTURES.items():
        if fixture in fixtures:
            lines.append(f'"path.{name}" = "{fixtures[fixture]}"')
    lines.append("")
    config_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", default="latest", choices=["latest", "next"])
    parser.add_argument("--url", default="http://localhost:1317")
    parser.add_argument("--schemathesis", default="schemathesis")
    parser.add_argument("--report", default=None, help="write the JSON report here")
    args = parser.parse_args()

    spec = REPO_ROOT / "sdk" / args.version / "api-reference" / "rest" / "openapi.yaml"
    if not spec.exists():
        print(f"no spec at {spec}", file=sys.stderr)
        return 1

    print(f"Discovering fixtures from {args.url}")
    try:
        fixtures = discover_fixtures(args.url)
    except Exception as error:  # noqa: BLE001 - any failure here is fatal and worth showing
        print(f"  could not reach the chain: {error}", file=sys.stderr)
        print("  start a local simapp with its API server enabled first", file=sys.stderr)
        return 1
    for name, value in fixtures.items():
        print(f"  {name}: {value}")

    # Discovered automatically from the working directory; there is no flag.
    config = Path.cwd() / "schemathesis.toml"
    write_config(config, spec, fixtures)

    command = [
        args.schemathesis,
        "run",
        str(spec),
        "--url",
        args.url,
        # The examples phase needs `example` values in the spec, which upstream
        # does not provide. Coverage is deterministic and visits every operation.
        "--phases",
        "coverage",
        "--continue-on-failure",
    ]
    if args.report:
        command += ["--report", "json", "--report-json-path", args.report]

    print(f"\nRunning {' '.join(command[:3])} against {args.url}")
    result = subprocess.run(command)

    if result.returncode != 0:
        print(
            "\nA failure here means a response did not match the schema this "
            "reference publishes. The node is the source of truth: the fix is "
            "almost always to the generator or the spec, not to the chain.",
            file=sys.stderr,
        )
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
